### ISSUE TITLE
primordials is not defined

### ISSUE THREAD

**Issue by javalireports** [mitre/caret#4]
when I run command - bower install I get the below error, please help:

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
←[90m    at fs.js:27:26←[39m
    at req_ (D:\Arvind\caret-master\node_modules\←[4mnatives←[24m\index.js:143:2
4)
    at Object.req [as require] (D:\Arvind\caret-master\node_modules\←[4mnatives←
[24m\index.js:55:10)
    at Object.<anonymous> (D:\Arvind\caret-master\node_modules\←[4mvinyl-fs←[24m
\node_modules\←[4mgraceful-fs←[24m\fs.js:1:37)
←[90m    at Module._compile (internal/modules/cjs/loader.js:959:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10
)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:815:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:727:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:852:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:74:18)←[39m

**Comment by liebesu** [comment]
i have same problem
